import type { Metadata } from "next";
import "./globals.css";

import localFont from "next/font/local";

// Font files can be colocated inside of `app`
const myFont = localFont({
  src: [
    {
      path: "./NeverMind-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./NeverMind-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./NeverMind-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "DanmuCat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="google-site-verification"
        content="-WMwHgwDcrghJdvwR8mxBsawDcF3tatuDRK5tzcrCJ4"
      />
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
